name: unit-tests and benchmarks

on: push

jobs:
  unit-tests:
    name: Run the unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Go version
        run: go version

      - name: Run go test ./...
        run: go test ./...

  benchmarks:
    name: Run the benchmarks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Go version
        run: go version

      - name: Run go test -bench=. ./...
        run: go test -bench=. ./...
